allowBuilds:
  esbuild: true
  sharp: true
autoInstallPeers: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
minimumReleaseAgeExclude:
  - '@kazupon/vp-config'
  - '@ox-jsdoc/**'
  - ox-jsdoc
  - '@ox-content/**'
overrides:
  vite@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
